/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zhaosc' at '18-7-9 下午2:59' with Gradle 2.14.1
 *
 * @author zhaosc, @date 18-7-9 下午2:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
